import { useState } from 'react';
import { Box, Button, CircularProgress, Drawer, IconButton, Stack, TextField, Typography } from '@mui/material';
import { Close, Memory, Send } from '@mui/icons-material';
import { askAssistant } from '../../api/client';

const prompts = ['What requires attention right now?', 'Explain the active investigation', 'Summarize maintenance risk'];

export function Assistant() {
  const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false);
  const [messages, setMessages] = useState([]);
  const submit = async (value = question) => { const text = value.trim(); if (!text || busy) return; setMessages((items) => [...items, { role: 'operator', text }]); setQuestion(''); setBusy(true); try { const response = await askAssistant(text); setMessages((items) => [...items, { role: 'assistant', text: response.data.answer }]); } catch { setMessages((items) => [...items, { role: 'assistant', text: 'I could not reach the operational knowledge service. Please try again.' }]); } finally { setBusy(false); } };
  return <><IconButton onClick={() => setOpen(true)} aria-label="Open RigOS Assistant" sx={{ position: 'fixed', zIndex: 1200, right: { xs: 18, md: 32 }, bottom: { xs: 18, md: 30 }, width: 58, height: 58, color: '#fff', background: 'linear-gradient(135deg,#1677FF,#6D5DFB)', boxShadow: '0 14px 36px rgba(22,119,255,.36)', '&:hover': { background: 'linear-gradient(135deg,#2685FF,#7C6CFF)', transform: 'translateY(-2px)' }, transition: 'all .2s ease' }}><Memory /></IconButton><Drawer anchor="right" open={open} onClose={() => setOpen(false)} PaperProps={{ sx: { width: { xs: '100%', sm: 460 }, p: 2.25, bgcolor: 'background.paper', backdropFilter: 'blur(26px)' } }}><Stack direction="row" justifyContent="space-between" alignItems="start"><Box><Typography variant="overline" color="primary" fontWeight={850} letterSpacing=".14em">RIGOS AI</Typography><Typography variant="h5">Operations copilot</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .4 }}>Ask about equipment, incidents, evidence, or recommended next actions.</Typography></Box><IconButton onClick={() => setOpen(false)}><Close /></IconButton></Stack><Stack direction="row" flexWrap="wrap" gap={.75} sx={{ mt: 2 }}>{prompts.map((prompt) => <Button key={prompt} size="small" variant="outlined" onClick={() => submit(prompt)}>{prompt}</Button>)}</Stack><Box sx={{ flex: 1, overflowY: 'auto', my: 2.25, pr: .5 }}>{messages.length ? <Stack spacing={1.3}>{messages.map((message, index) => <Box key={index} sx={{ alignSelf: message.role === 'operator' ? 'flex-end' : 'flex-start', maxWidth: '90%', p: 1.3, borderRadius: 2.2, bgcolor: message.role === 'operator' ? 'primary.main' : 'action.hover', color: message.role === 'operator' ? '#fff' : 'text.primary', whiteSpace: 'pre-wrap' }}>{message.text}</Box>)}{busy && <CircularProgress size={20} />}</Stack> : <Box sx={{ pt: 8, textAlign: 'center' }}><Memory sx={{ color: 'primary.main', fontSize: 44 }} /><Typography fontWeight={750} sx={{ mt: 1 }}>How can I help?</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>I use RigOS operational knowledge and live context.</Typography></Box>}</Box><Stack direction="row" spacing={1}><TextField fullWidth placeholder="Ask RigOS…" value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} /><Button variant="contained" onClick={() => submit()} disabled={!question.trim() || busy}><Send /></Button></Stack></Drawer></>;
}
