# Add a way to trigger maintenance planning
import streamlit as st
from frontend_services.maintenance_adapter import get_maintenance_plan
from ui_helpers import metric_card, page_heading, render_sidebar, setup_page, status_chip

setup_page("Maintenance Planner")
render_sidebar("Maintenance Planner")
page_heading("WORK ORCHESTRATION", "Maintenance Planner", "Turn MAO task state and recommendations into an executable maintenance view.")

plan = get_maintenance_plan()

# ✅ If no tasks, show a way to generate them
if not plan.get("tasks"):
    st.info("No maintenance tasks have been generated yet. Trigger an incident to generate tasks.")
    
    # ✅ Add a button to trigger a maintenance incident
    if st.button("🚨 Generate Maintenance Task", use_container_width=True):
        from frontend_services.incident_adapter import trigger_incident
        result = trigger_incident("maintenance")
        st.success("Maintenance incident triggered! Refresh the page to see tasks.")
        st.rerun()

# ... rest of the page

left, right = st.columns([1.7, 1])
with left:
    st.markdown("<div class='section-label'>RECOMMENDED WORK PLAN</div>", unsafe_allow_html=True)
    if plan["tasks"]:
        st.dataframe(plan["tasks"], hide_index=True, height=250, width="stretch")
    else:
        st.info("No MAO maintenance tasks have been generated yet.")

with right:
    st.markdown("<div class='section-label'>PLANNING STATUS</div>", unsafe_allow_html=True)
    st.metric("Latest priority", plan["priority"])
    st.metric("Estimated downtime", plan["downtime"])
    st.caption("Read-only view of tasks generated by the shared MAO runtime.")

st.write("")
left, right = st.columns([1.55, 1])
with left:
    st.markdown("<div class='section-label'>MAINTENANCE TIMELINE</div>", unsafe_allow_html=True)
    if plan["tasks"]:
        for task in plan["tasks"]:
            tone = "Critical" if task["Priority"] == "P1" else "Info"
            st.markdown(
                f"<div class='timeline-row'><span class='muted'>{task['Priority']}</span>"
                f"<span class='timeline-dot'></span><div class='panel'><b>{task['Work order']}</b> "
                f"&nbsp; {status_chip(tone)}<br><span class='muted'>Asset: {task['Asset']} "
                f"· Owner: {task['Owner']} · State: {task['State']}</span></div></div>",
                unsafe_allow_html=True,
            )
    else:
        st.caption("The timeline will populate when a maintenance workflow creates tasks.")

with right:
    st.markdown("<div class='section-label'>AI SCHEDULING RATIONALE</div>", unsafe_allow_html=True)
    if plan["rationale"]:
        st.markdown(
            "<div class='panel'><b>Latest MAO recommendations</b><ul>"
            + "".join(f"<li>{item}</li>" for item in plan["rationale"])
            + "</ul></div>",
            unsafe_allow_html=True,
        )
    else:
        st.info("No planning-agent recommendation is available yet.")