import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import streamlit as st
from ui_helpers import page_heading, render_sidebar, setup_page, metric_card
from frontend_services.backend_api import api


setup_page("Configuration Dashboard")
render_sidebar("Configuration")

page_heading(
    "DYNAMIC CONFIGURATION",
    "Gemini-Generated Settings",
    "View and refresh operational parameters generated by Gemini.",
)

# -------------------------
# API Key Status Section
# -------------------------

st.markdown("### 🔑 API Key Status")

try:
    from services.llm import LLMManager
    llm = LLMManager()
    status = llm.get_key_status()
    
    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Keys", status["total_keys"])
    with col2:
        st.metric("Available Keys", status["summary"]["available_keys"])
    with col3:
        st.metric("Active Keys", status["summary"]["active_keys"])
    with col4:
        success_rate = status["summary"]["overall_success_rate"]
        st.metric("Success Rate", f"{success_rate:.1f}%")
    
    # Detailed key table
    key_data = []
    for k in status["keys"]:
        # Determine status emoji
        if k["is_available"]:
            status_emoji = "🟢 Active"
        elif not k["is_active"]:
            status_emoji = "🔴 Cooldown"
        else:
            status_emoji = "🟡 Degraded"
        
        key_data.append({
            "#": k["index"],
            "Key": k["key_preview"],
            "Status": status_emoji,
            "Success Rate": k["success_rate"],
            "Requests": k["total_requests"],
            "Failures": k["failures"],
            "Last Used": k["last_used"],
            "Last Error": k["last_error"][:40] + "..." if len(k["last_error"] or "") > 40 else (k["last_error"] or "None"),
        })
    
    if key_data:
        st.dataframe(key_data, hide_index=True, use_container_width=True)
    
    # Reset key button
    st.markdown("#### Reset a Failed Key")
    col1, col2 = st.columns([2, 1])
    with col1:
        key_index = st.number_input("Key Number to Reset", min_value=1, max_value=status["total_keys"], value=1, step=1)
    with col2:
        if st.button("🔄 Reset Key", use_container_width=True):
            if llm.reset_key(key_index):
                st.success(f"✅ Key {key_index} reset successfully!")
                st.rerun()
            else:
                st.error(f"❌ Failed to reset key {key_index}")
    
    st.divider()
    
except Exception as e:
    st.warning(f"Could not load API key status: {e}")
    st.divider()

# -------------------------
# Current Configuration Section
# -------------------------

st.markdown("### 📊 Current Configuration")

# Display thresholds for different asset types
asset_types = ["Pump", "Compressor", "Tank", "Valve", "Pipeline", "Heat Exchanger"]

for asset_type in asset_types:
    with st.expander(f"{asset_type} Thresholds", expanded=False):
        try:
            thresholds = api.get_dynamic_thresholds(asset_type)
            col1, col2, col3, col4, col5 = st.columns(5)
            with col1:
                st.metric("Pressure Max", f"{thresholds.get('pressure_max', 'N/A')} PSI")
            with col2:
                st.metric("Temperature Max", f"{thresholds.get('temperature_max', 'N/A')} °C")
            with col3:
                st.metric("Gas Max", f"{thresholds.get('gas_max', 'N/A')} ppm")
            with col4:
                st.metric("Vibration Max", f"{thresholds.get('vibration_max', 'N/A')} mm/s")
            with col5:
                st.metric("Flow Min", f"{thresholds.get('flow_min', 'N/A')} L/min")
        except Exception as e:
            st.error(f"Error loading thresholds for {asset_type}: {e}")

st.divider()

# Workflow sequences
st.markdown("### 🔄 Workflow Sequences")

incident_types = ["Pressure Spike", "Gas Leak", "High Temperature", "High Vibration", "Flow Restriction"]

for incident_type in incident_types:
    with st.expander(f"{incident_type} Workflow", expanded=False):
        try:
            sequence = api.get_workflow_sequence(incident_type.lower())
            st.write(" → ".join(sequence))
        except Exception as e:
            st.error(f"Error loading workflow for {incident_type}: {e}")

st.divider()

# Refresh button
col1, col2, col3 = st.columns([1, 1, 2])
with col1:
    if st.button("🔄 Refresh All Configs", use_container_width=True):
        with st.spinner("Refreshing configurations from Gemini..."):
            result = api.refresh_config()
            st.success("Config cache cleared and refreshed!")
            st.rerun()

with col2:
    status = api.get_simulation_status()
    st.metric("Simulation Status", "Running" if status.get("running") else "Stopped")

st.caption("⚠️ Configurations are generated by Gemini and may vary between refreshes. Refresh to get new values.")