import { useMemo, useState } from 'react';
import {
  Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogContent, Divider, Drawer, IconButton,
  InputAdornment, LinearProgress, Menu, MenuItem, Paper, Stack, TextField, Tooltip, Typography,
} from '@mui/material';
import { Close, MoreHoriz, Search } from '@mui/icons-material';
import { rigosV2Tokens, semanticTone } from './tokens';

const { color, radius, elevation, motion, typography } = rigosV2Tokens;
const tone = (name = 'neutral') => semanticTone[name] || semanticTone.neutral;
const clamp = (value) => Math.max(0, Math.min(100, value || 0));

export function V2PrimaryButton({ children, loading, disabled, sx, ...props }) { return <Button variant="contained" disabled={disabled || loading} sx={{ px: 2, color: '#fff', background: `linear-gradient(135deg, ${color.blue}, ${color.violet})`, transition: `transform ${motion.fast} ${motion.standard}, box-shadow ${motion.fast} ${motion.standard}`, '&:hover': { transform: 'translateY(-1px)', boxShadow: elevation.glowViolet }, ...sx }} {...props}>{loading ? <CircularProgress size={17} color="inherit" /> : children}</Button>; }
export function V2GhostButton({ children, loading, disabled, sx, ...props }) { return <Button variant="text" disabled={disabled || loading} sx={{ color: 'text.secondary', '&:hover': { color: 'text.primary', bgcolor: 'action.hover' }, ...sx }} {...props}>{loading ? <CircularProgress size={17} /> : children}</Button>; }
export function V2CommandButton({ label = 'Search or run a command…', shortcut = '⌘ K', onClick, disabled, sx }) { return <Button onClick={onClick} disabled={disabled} variant="outlined" sx={{ justifyContent: 'space-between', minWidth: 260, color: 'text.secondary', borderColor: 'divider', bgcolor: 'action.hover', '&:hover': { borderColor: color.cyan, color: 'text.primary', transform: 'translateY(-1px)' }, ...sx }}>{label}<Typography component="span" sx={{ ...typography.mono, opacity: .65 }}>{shortcut}</Typography></Button>; }

export function V2StatusBadge({ label, tone: toneName = 'neutral', pulse = false, loading = false, sx }) { const t = tone(toneName); return <Chip label={loading ? 'Loading…' : label} size="small" sx={{ color: t.main, bgcolor: t.soft, fontWeight: 800, letterSpacing: '.07em', '&::before': { content: '""', width: 6, height: 6, borderRadius: 9, display: 'inline-block', bgcolor: t.main, mr: .75, animation: pulse ? 'rigos-v2-pulse 1.6s infinite' : 'none' }, ...sx }} />; }
export function V2AlertChip({ children, tone: toneName = 'warning', active, sx }) { const t = tone(toneName); return <Chip label={children} size="small" sx={{ color: t.main, bgcolor: active ? t.soft : 'transparent', border: `1px solid ${t.main}55`, fontWeight: 750, ...sx }} />; }

export function V2GlassCard({ children, hover = true, active = false, loading = false, sx, ...props }) { return <Card {...props} className={active ? 'rigos-v2-glow' : undefined} sx={{ overflow: 'hidden', borderRadius: radius.lg, bgcolor: 'background.paper', boxShadow: active ? elevation.glowCyan : elevation.low, transition: `transform ${motion.normal} ${motion.standard}, box-shadow ${motion.normal} ${motion.standard}`, ...(hover && { '&:hover': { transform: 'translateY(-3px)', boxShadow: elevation.medium } }), ...sx }}>{loading ? <Box className="rigos-v2-shimmer" sx={{ height: 3 }} /> : null}{children}</Card>; }
export function V2FloatingPanel({ children, active, sx }) { return <Paper className={active ? 'rigos-v2-enter' : undefined} sx={{ p: 2, borderRadius: radius.xl, boxShadow: elevation.medium, ...sx }}>{children}</Paper>; }
export function V2InspectorPanel({ open, onClose, title, subtitle, children, width = 460 }) { return <Drawer anchor="right" open={open} onClose={onClose} PaperProps={{ sx: { width: { xs: '100%', sm: width }, p: 2.5, bgcolor: 'background.paper', backdropFilter: 'blur(28px)' } }}><Stack direction="row" justifyContent="space-between"><Box><Typography sx={typography.caption} color="text.secondary">INSPECTOR</Typography><Typography variant="h5">{title}</Typography>{subtitle && <Typography variant="body2" color="text.secondary">{subtitle}</Typography>}</Box><IconButton onClick={onClose}><Close /></IconButton></Stack><Divider sx={{ my: 2 }} />{children}</Drawer>; }

export function V2HealthRing({ value, label = 'Health', size = 112, loading = false }) { const percent = clamp(value); const ringTone = percent < 50 ? tone('danger').main : percent < 80 ? tone('warning').main : tone('success').main; return <Box sx={{ width: size, height: size, borderRadius: '50%', display: 'grid', placeItems: 'center', background: `conic-gradient(${ringTone} ${percent * 3.6}deg, rgba(128,148,177,.16) 0)` }}><Box sx={{ width: size - 18, height: size - 18, borderRadius: '50%', display: 'grid', placeItems: 'center', bgcolor: 'background.paper', textAlign: 'center' }}>{loading ? <CircularProgress size={22} /> : <><Typography sx={{ fontSize: size * .22, lineHeight: 1, fontWeight: 800, color: ringTone }}>{Math.round(percent)}%</Typography><Typography variant="caption" color="text.secondary">{label}</Typography></>}</Box></Box>; }
export function V2ProgressIndicator({ value, label, tone: toneName = 'info', loading = false, sx }) { const t = tone(toneName); return <Box sx={sx}>{label && <Stack direction="row" justifyContent="space-between" sx={{ mb: .6 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="caption" sx={{ color: t.main }}>{Math.round(clamp(value))}%</Typography></Stack>}<LinearProgress variant={loading ? 'indeterminate' : 'determinate'} value={clamp(value)} sx={{ height: 6, borderRadius: 9, bgcolor: 'action.hover', '& .MuiLinearProgress-bar': { bgcolor: t.main, borderRadius: 9 } }} /></Box>; }
export function V2ConfidenceMeter({ value, label = 'Confidence', loading }) { return <V2ProgressIndicator value={value} label={label} tone="violet" loading={loading} />; }

export function V2AIAgentCard({ name, task, state = 'idle', confidence, evidenceCount, active, loading, onClick }) {
  const stateTone = state === 'failed' ? 'danger' : state === 'working' ? 'info' : state === 'complete' ? 'success' : 'neutral';
  return (
    <V2GlassCard hover active={active} loading={loading} onClick={onClick} sx={{ cursor: onClick ? 'pointer' : 'default' }}>
      <CardContent sx={{ p: 1.6 }}>
        <Stack direction="row" justifyContent="space-between">
          <Stack direction="row" spacing={1} alignItems="center">
            <Box sx={{ width: 30, height: 30, display: 'grid', placeItems: 'center', borderRadius: 2, color: tone(stateTone).main, bgcolor: tone(stateTone).soft, fontWeight: 850 }}>{name?.slice(0, 1)}</Box>
            <Box>
              <Typography sx={typography.title}>{name}</Typography>
              <Typography variant="caption" color="text.secondary">{task || 'Standing by'}</Typography>
            </Box>
          </Stack>
          <V2StatusBadge label={state} tone={stateTone} pulse={state === 'working'} />
        </Stack>
        {confidence != null && <V2ConfidenceMeter value={confidence} label={evidenceCount != null ? `${evidenceCount} evidence items` : 'Confidence'} />}
      </CardContent>
    </V2GlassCard>
  );
}
export function V2Timeline({ items = [], loading = false, onSelect }) { return <Stack spacing={0}>{items.map((item, index) => { const t = tone(item.tone || (item.state === 'failed' ? 'danger' : item.state === 'active' ? 'info' : 'success')); return <Box key={item.id || index} onClick={() => onSelect?.(item)} sx={{ display: 'flex', gap: 1.3, pb: index === items.length - 1 ? 0 : 2, cursor: onSelect ? 'pointer' : 'default' }}><Box sx={{ width: 14, display: 'flex', flexDirection: 'column', alignItems: 'center' }}><Box sx={{ mt: .55, width: 9, height: 9, borderRadius: 9, bgcolor: t.main, boxShadow: item.state === 'active' ? `0 0 15px ${t.main}` : 'none' }} />{index < items.length - 1 && <Box sx={{ width: 1, flex: 1, minHeight: 20, bgcolor: 'divider', my: .75 }} />}</Box><Box flex={1}><Stack direction="row" justifyContent="space-between"><Typography sx={typography.title}>{item.title}</Typography><Typography variant="caption" color="text.secondary">{item.time}</Typography></Stack><Typography variant="body2" color="text.secondary">{item.description}</Typography>{item.meta && <Typography sx={{ ...typography.mono, color: t.main, mt: .5 }}>{item.meta}</Typography>}</Box></Box>; })}{loading && <LinearProgress />}</Stack>; }
export function V2EvidenceCard({ title, source, confidence, children, expanded = false, onClick }) { return <V2GlassCard hover onClick={onClick} sx={{ cursor: onClick ? 'pointer' : 'default', boxShadow: expanded ? elevation.medium : elevation.low }}><CardContent sx={{ p: 1.5 }}><Stack direction="row" justifyContent="space-between"><Box><Typography sx={typography.title}>{title}</Typography><Typography variant="caption" color="text.secondary">{source}</Typography></Box>{confidence != null && <V2StatusBadge label={`${Math.round(confidence)}%`} tone="info" />}</Stack>{children && <Box sx={{ mt: 1.1 }}>{children}</Box>}</CardContent></V2GlassCard>; }
export function V2RecommendationCard({ title = 'Recommended next action', recommendation, tone: toneName = 'info', action, loading }) { const t = tone(toneName); return <V2GlassCard loading={loading} sx={{ borderLeft: `3px solid ${t.main}` }}><CardContent><Typography sx={{ ...typography.caption, color: t.main }}>{title}</Typography><Typography sx={{ ...typography.title, mt: .6 }}>{recommendation}</Typography>{action && <Box sx={{ mt: 1.5 }}>{action}</Box>}</CardContent></V2GlassCard>; }

export function V2MetricStrip({ metrics = [] }) { return <Stack direction={{ xs: 'column', md: 'row' }} divider={<Divider flexItem orientation="vertical" />} sx={{ borderRadius: radius.lg, overflow: 'hidden', bgcolor: 'background.paper', boxShadow: elevation.low }}>{metrics.map((metric, index) => <Box key={metric.label || index} sx={{ px: 2.25, py: 1.65, flex: 1 }}><Typography sx={{ ...typography.caption, color: 'text.secondary' }}>{metric.label}</Typography><Typography sx={{ ...typography.heading, color: metric.color || 'text.primary', mt: .2 }}>{metric.loading ? '—' : metric.value}</Typography><Typography variant="caption" color="text.secondary">{metric.detail}</Typography></Box>)}</Stack>; }
export function V2FacilityNode({ label, type, health, active, onClick, loading }) { const healthTone = health < 50 ? 'danger' : health < 80 ? 'warning' : 'success'; const t = tone(healthTone); return <Box onClick={onClick} className={active ? 'rigos-v2-glow' : undefined} sx={{ p: 1.25, minWidth: 108, borderRadius: radius.md, bgcolor: t.soft, border: `1px solid ${t.main}44`, cursor: onClick ? 'pointer' : 'default', transition: `transform ${motion.fast} ${motion.standard}`, '&:hover': onClick ? { transform: 'translateY(-2px)' } : {}, opacity: loading ? .65 : 1 }}><Box sx={{ width: 8, height: 8, borderRadius: 9, bgcolor: t.main, mb: .8 }} /><Typography sx={typography.title}>{label}</Typography><Typography variant="caption" color="text.secondary">{type} · {loading ? 'syncing' : `${Math.round(health)}%`}</Typography></Box>; }

export function V2NavigationItem({ icon, label, active, disabled, onClick }) { return <Button disabled={disabled} onClick={onClick} startIcon={icon} sx={{ minWidth: 0, width: '100%', justifyContent: 'flex-start', color: active ? 'primary.main' : 'text.secondary', bgcolor: active ? 'rgba(40,124,255,.10)' : 'transparent', borderRadius: radius.md, '&:hover': { bgcolor: 'action.hover', color: 'text.primary' } }}>{label}</Button>; }
export function V2SearchBar({ value, onChange, placeholder = 'Search…', loading, onSubmit, sx }) { return <TextField value={value} onChange={(event) => onChange?.(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && onSubmit?.(value)} placeholder={placeholder} fullWidth InputProps={{ startAdornment: <InputAdornment position="start">{loading ? <CircularProgress size={16} /> : <Search fontSize="small" />}</InputAdornment> }} sx={{ '& .MuiOutlinedInput-root': { borderRadius: radius.md, bgcolor: 'action.hover' }, ...sx }} />; }
export function V2SectionHeader({ eyebrow, title, description, action }) { return <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'end' }} spacing={1.5}><Box>{eyebrow && <Typography sx={{ ...typography.caption, color: color.cyan }}>{eyebrow}</Typography>}<Typography sx={typography.heading}>{title}</Typography>{description && <Typography variant="body2" color="text.secondary" sx={{ mt: .6, maxWidth: 680 }}>{description}</Typography>}</Box>{action}</Stack>; }
export function V2Toolbar({ children, floating = false, sx }) { return <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} spacing={1} sx={{ p: 1, borderRadius: radius.lg, bgcolor: floating ? 'background.paper' : 'transparent', boxShadow: floating ? elevation.low : 'none', ...sx }}>{children}</Stack>; }

export function V2Modal({ open, onClose, title, children, actions, maxWidth = 'sm' }) { return <Dialog open={open} onClose={onClose} fullWidth maxWidth={maxWidth} PaperProps={{ sx: { borderRadius: radius.xl, bgcolor: 'background.paper', backdropFilter: 'blur(28px)' } }}><DialogContent sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Typography variant="h5">{title}</Typography><IconButton onClick={onClose}><Close /></IconButton></Stack><Box sx={{ mt: 2 }}>{children}</Box>{actions && <Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 2.5 }}>{actions}</Stack>}</DialogContent></Dialog>; }
export function V2CommandPalette({ open, onClose, commands = [] }) { const [query, setQuery] = useState(''); const visible = useMemo(() => commands.filter((command) => `${command.label} ${command.description || ''}`.toLowerCase().includes(query.toLowerCase())), [commands, query]); return <V2Modal open={open} onClose={onClose} title="Command palette" maxWidth="sm"><V2SearchBar value={query} onChange={setQuery} placeholder="Search commands…" /><Stack spacing={.5} sx={{ mt: 1.5 }}>{visible.map((command, index) => <Box key={command.id || index} onClick={() => { command.onSelect?.(); onClose?.(); }} sx={{ p: 1.2, borderRadius: radius.md, cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' } }}><Typography sx={typography.title}>{command.label}</Typography><Typography variant="caption" color="text.secondary">{command.description}</Typography></Box>)}</Stack></V2Modal>; }
export function V2DesignDrawer({ open, onClose, title, children, width }) { return <V2InspectorPanel open={open} onClose={onClose} title={title} width={width}>{children}</V2InspectorPanel>; }
export function V2ContextMenu({ anchorEl, onClose, items = [] }) { return <Menu anchorEl={anchorEl} open={Boolean(anchorEl)} onClose={onClose}>{items.map((item, index) => <MenuItem key={item.label || index} disabled={item.disabled} onClick={() => { item.onClick?.(); onClose?.(); }}>{item.label}</MenuItem>)}</Menu>; }
export function V2HoverCard({ title, description, children }) { return <Tooltip title={<Box sx={{ p: .4 }}><Typography sx={typography.title}>{title}</Typography><Typography variant="caption">{description}</Typography></Box>} arrow><Box component="span">{children}</Box></Tooltip>; }
export function V2MoreMenu({ items }) { const [anchorEl, setAnchorEl] = useState(null); return <><IconButton onClick={(event) => setAnchorEl(event.currentTarget)}><MoreHoriz /></IconButton><V2ContextMenu anchorEl={anchorEl} onClose={() => setAnchorEl(null)} items={items} /></>; }
