import { useMemo, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import {
  Box, Dialog, DialogContent, Drawer, IconButton, InputAdornment, LinearProgress,
  Stack, TextField, Typography,
} from '@mui/material';
import { Close, Search, Terminal } from '@mui/icons-material';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { semanticTone } from './tokens';

const spring = { type: 'spring', stiffness: 420, damping: 32, mass: 0.7 };
const toneFor = (name) => semanticTone[name] || semanticTone.neutral;
const MotionBox = motion.create(Box);

export function RigCard({ children, interactive = false, active = false, padding = 2, sx, ...props }) {
  const reduced = useReducedMotion();
  return <MotionBox {...props} className="rig-card" initial={false} whileHover={interactive && !reduced ? { y: -2 } : undefined} whileTap={interactive && !reduced ? { scale: 0.995 } : undefined} transition={spring} sx={{ p: padding, cursor: interactive ? 'pointer' : 'default', ...(active && { borderColor: 'rgba(88,216,255,.46)', boxShadow: '0 0 0 1px rgba(88,216,255,.08), 0 14px 40px rgba(0,0,0,.18)' }), ...sx }}>{children}</MotionBox>;
}

export function MetricCard({ label, value, detail, trend, tone = 'neutral', loading = false, children }) {
  const t = toneFor(tone);
  return <RigCard className="rig-metric" padding={2} aria-busy={loading}><Typography className="rig-label">{label}</Typography><Stack direction="row" alignItems="baseline" spacing={1} sx={{ mt: .7 }}><Typography className="rig-metric-value">{loading ? '—' : value}</Typography>{trend && <Typography className="rig-metric-trend" sx={{ color: t.main }}>{trend}</Typography>}</Stack>{detail && <Typography variant="caption" color="text.secondary">{detail}</Typography>}{children}</RigCard>;
}

export function StatusBadge({ label, tone = 'neutral', live = false, sx }) { const t = toneFor(tone); return <Box component="span" className="rig-badge" sx={{ color: t.main, backgroundColor: t.soft, ...sx }}><motion.i aria-hidden animate={live ? { opacity: [1, .45, 1], scale: [1, .82, 1] } : false} transition={{ duration: 1.7, repeat: Infinity }} style={{ backgroundColor: t.main }} />{label}</Box>; }

export function AIAgentCard({ name, description, state = 'idle', confidence, action, icon }) {
  const stateTone = { working: 'info', complete: 'success', failed: 'danger', waiting: 'warning' }[state] || 'neutral';
  return <RigCard interactive className="rig-agent-card"><Stack direction="row" justifyContent="space-between" spacing={1.5}><Stack direction="row" spacing={1.25} alignItems="center"><Box className="rig-agent-icon">{icon || name?.slice(0, 1)}</Box><Box><Typography fontWeight={750}>{name}</Typography><Typography variant="caption" color="text.secondary">{description || 'Standing by'}</Typography></Box></Stack><StatusBadge label={state} tone={stateTone} live={state === 'working'} /></Stack>{confidence != null && <RigProgress label="Confidence" value={confidence} tone={stateTone} sx={{ mt: 2 }} />}{action && <Box sx={{ mt: 1.5 }}>{action}</Box>}</RigCard>;
}

export function TimelineCard({ items = [], onSelect }) { return <RigCard padding={2}>{items.map((item, index) => { const t = toneFor(item.tone || 'neutral'); return <MotionBox key={item.id || index} role={onSelect ? 'button' : undefined} tabIndex={onSelect ? 0 : undefined} onClick={() => onSelect?.(item)} whileHover={onSelect ? { x: 2 } : undefined} className="rig-timeline-row"><Box className="rig-timeline-rail"><Box className="rig-timeline-dot" sx={{ backgroundColor: t.main }} />{index < items.length - 1 && <Box className="rig-timeline-line" />}</Box><Box sx={{ pb: index < items.length - 1 ? 2 : 0, flex: 1 }}><Stack direction="row" justifyContent="space-between" spacing={2}><Typography fontWeight={700}>{item.title}</Typography><Typography className="rig-mono">{item.time}</Typography></Stack>{item.description && <Typography variant="body2" color="text.secondary" sx={{ mt: .4 }}>{item.description}</Typography>}</Box></MotionBox>; })}</RigCard>; }

export function EmptyState({ title, description, action, icon = <Terminal fontSize="small" /> }) { return <RigCard className="rig-empty" padding={3}><Box className="rig-empty-icon">{icon}</Box><Typography fontWeight={750}>{title}</Typography><Typography variant="body2" color="text.secondary" sx={{ maxWidth: 360 }}>{description}</Typography>{action}</RigCard>; }

export function RigProgress({ label, value, tone = 'info', sx }) { const t = toneFor(tone); return <Box sx={sx}>{label && <Stack direction="row" justifyContent="space-between" sx={{ mb: .65 }}><Typography className="rig-label">{label}</Typography><Typography className="rig-mono" sx={{ color: t.main }}>{Math.round(value || 0)}%</Typography></Stack>}<LinearProgress variant="determinate" value={Math.max(0, Math.min(100, value || 0))} sx={{ '& .MuiLinearProgress-bar': { backgroundColor: t.main } }} /></Box>; }

export function TelemetryChart({ data = [], dataKey = 'value', xKey = 'time', label, tone = 'info', height = 190 }) { const t = toneFor(tone); return <RigCard padding={2} className="rig-chart"><Stack direction="row" justifyContent="space-between" sx={{ mb: 1 }}><Typography className="rig-label">{label}</Typography><StatusBadge label="Live" tone={tone} live /></Stack><Box sx={{ height }}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 6, right: 4, left: -22, bottom: 0 }}><defs><linearGradient id={`rig-chart-${dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={t.main} stopOpacity={.24} /><stop offset="100%" stopColor={t.main} stopOpacity={0} /></linearGradient></defs><XAxis dataKey={xKey} tickLine={false} axisLine={false} tick={{ fill: '#718096', fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#718096', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#161c25', border: '1px solid rgba(255,255,255,.12)', borderRadius: 10 }} /><Area type="monotone" dataKey={dataKey} stroke={t.main} strokeWidth={2} fill={`url(#rig-chart-${dataKey})`} isAnimationActive /></AreaChart></ResponsiveContainer></Box></RigCard>; }

export function RigDrawer({ open, onClose, title, subtitle, children, width = 480 }) { return <Drawer anchor="right" open={open} onClose={onClose} PaperProps={{ className: 'rig-overlay', sx: { width: { xs: '100%', sm: width } } }}><OverlayHeader title={title} subtitle={subtitle} onClose={onClose} />{children}</Drawer>; }
export function RigModal({ open, onClose, title, subtitle, children, actions, maxWidth = 'sm' }) { return <Dialog open={open} onClose={onClose} fullWidth maxWidth={maxWidth} TransitionComponent={undefined} PaperProps={{ className: 'rig-overlay' }}><DialogContent sx={{ p: 2.5 }}><OverlayHeader title={title} subtitle={subtitle} onClose={onClose} />{children}{actions && <Stack direction="row" justifyContent="flex-end" spacing={1.25} sx={{ mt: 2.5 }}>{actions}</Stack>}</DialogContent></Dialog>; }
function OverlayHeader({ title, subtitle, onClose }) { return <Stack direction="row" justifyContent="space-between" spacing={2} sx={{ mb: 2.25 }}><Box><Typography className="rig-label">SYSTEM INTERFACE</Typography><Typography variant="h6" sx={{ mt: .35 }}>{title}</Typography>{subtitle && <Typography variant="body2" color="text.secondary">{subtitle}</Typography>}</Box><IconButton aria-label="Close" onClick={onClose}><Close /></IconButton></Stack>; }

export function Toast({ open, title, message, tone = 'info', onClose }) { const t = toneFor(tone); return <AnimatePresence>{open && <MotionBox className="rig-toast" role="status" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={spring}><Box className="rig-toast-rule" sx={{ backgroundColor: t.main }} /><Box><Typography fontWeight={750}>{title}</Typography>{message && <Typography variant="body2" color="text.secondary">{message}</Typography>}</Box><IconButton size="small" onClick={onClose} aria-label="Dismiss notification"><Close fontSize="small" /></IconButton></MotionBox>}</AnimatePresence>; }
export function NotificationItem({ title, message, time, tone = 'info', unread = false, onClick }) { const t = toneFor(tone); return <MotionBox whileHover={{ x: 2 }} onClick={onClick} className="rig-notification" sx={{ cursor: onClick ? 'pointer' : 'default' }}><Box className="rig-notification-dot" sx={{ backgroundColor: unread ? t.main : 'transparent' }} /><Box flex={1}><Stack direction="row" justifyContent="space-between" spacing={2}><Typography fontWeight={700}>{title}</Typography><Typography className="rig-mono">{time}</Typography></Stack><Typography variant="body2" color="text.secondary">{message}</Typography></Box></MotionBox>; }

export function CommandPalette({ open, onClose, commands = [] }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => commands.filter((command) => `${command.label} ${command.description || ''}`.toLowerCase().includes(query.toLowerCase())), [commands, query]); return <RigModal open={open} onClose={onClose} title="Command palette" subtitle="Search actions and navigate the system"><RigSearch autoFocus value={query} onChange={setQuery} placeholder="Type a command…" /><Box sx={{ mt: 1.5 }}>{filtered.map((command, index) => <MotionBox key={command.id || index} whileHover={{ x: 2, backgroundColor: 'rgba(255,255,255,.045)' }} onClick={() => { command.onSelect?.(); onClose?.(); }} className="rig-command"><Box><Typography fontWeight={700}>{command.label}</Typography>{command.description && <Typography variant="caption" color="text.secondary">{command.description}</Typography>}</Box>{command.shortcut && <kbd>{command.shortcut}</kbd>}</MotionBox>)}</Box></RigModal>; }
export function RigSearch({ value, onChange, placeholder = 'Search…', onSubmit, ...props }) { return <TextField {...props} value={value} onChange={(event) => onChange?.(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && onSubmit?.(value)} placeholder={placeholder} fullWidth size="small" InputProps={{ startAdornment: <InputAdornment position="start"><Search fontSize="small" /></InputAdornment> }} className="rig-search" />; }
export function RigToolbar({ children, floating = false, sx }) { return <MotionBox layout className={floating ? 'rig-toolbar rig-toolbar-float' : 'rig-toolbar'} sx={sx}>{children}</MotionBox>; }
export function SectionHeader({ eyebrow, title, description, action }) { return <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'end' }} spacing={1.5} className="rig-section-header"><Box>{eyebrow && <Typography className="rig-label">{eyebrow}</Typography>}<Typography variant="h5" sx={{ mt: .45 }}>{title}</Typography>{description && <Typography variant="body2" color="text.secondary" sx={{ mt: .6, maxWidth: 680 }}>{description}</Typography>}</Box>{action}</Stack>; }
export function PageHeader({ eyebrow, title, description, actions }) { return <Stack direction={{ xs: 'column', lg: 'row' }} justifyContent="space-between" alignItems={{ lg: 'end' }} spacing={2.5} className="rig-page-header"><Box>{eyebrow && <Typography className="rig-label">{eyebrow}</Typography>}<Typography component="h1" className="rig-page-title">{title}</Typography>{description && <Typography color="text.secondary" sx={{ mt: 1.25, maxWidth: 720 }}>{description}</Typography>}</Box>{actions && <Stack direction="row" spacing={1}>{actions}</Stack>}</Stack>; }
export function FloatingPanel({ children, position = 'bottom-right', sx }) { return <MotionBox className={`rig-floating-panel is-${position}`} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={spring} sx={sx}>{children}</MotionBox>; }
