import { useEffect, useRef, useState } from 'react';
import { Box, Button, IconButton, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { ArticleOutlined, CommentOutlined, DevicesOutlined, ExpandMoreOutlined, FactCheckOutlined, FilterListOutlined, MemoryOutlined, MoreHorizOutlined, PlayArrowOutlined, SearchOutlined, ShieldOutlined, WarningAmberOutlined } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { useWorkspace } from '../../context/WorkspaceContext';
import { useObjectContext } from '../../context/ObjectContext';
import { navigateTo } from '../../context/objectNavigation';
import { OperatorDecisionBar, EvidenceLineage, buildEvidenceFacts, DecisionHistory, ProvenanceBadge } from '../accountability';
import { Status, MiniGraph, EvidenceItem, formatTime, label, round, safeReasoning } from './shared';

export function IncidentManagement({ incidents, telemetry, provenance = 'live' }) {
  const navigate = useNavigate(); const objectApi = useObjectContext();
  const timelineRef = useRef(null);
  const [query, setQuery] = useState(''); const [severity, setSeverity] = useState('all'); const { workspace, setWorkspaceValue } = useWorkspace(); const selectedId = objectApi.selection.incidentId ?? workspace.incidentSelection ?? null; const setSelectedId = (id) => { objectApi.setSelection({ incidentId: id }); setWorkspaceValue('incidentSelection', id); }; const [reasoning, setReasoning] = useState(false); const [replay, setReplay] = useState(false);
  const visible = incidents.filter((item) => `${item.incident_type || ''} ${item.asset_name || ''} ${item.severity || ''}`.toLowerCase().includes(query.toLowerCase()) && (severity === 'all' || String(item.severity).toLowerCase() === severity)); const incident = visible.find((item) => item.id === selectedId) || visible[0];
  useEffect(() => {
    if (!incident?.id) return undefined;
    const timer = requestAnimationFrame(() => timelineRef.current?.querySelector?.('.incident-event')?.scrollIntoView?.({ block: 'nearest', behavior: 'smooth' }));
    return () => cancelAnimationFrame(timer);
  }, [incident?.id]);
  if (!incident) return <Box className="twin-empty"><WarningAmberOutlined fontSize="large" /><Typography fontWeight={800}>No incident records in this view</Typography><Typography variant="body2">The live incident queue will populate when detection or operator escalation creates a case.</Typography></Box>;
  const confidence = round(Number(incident.confidence ?? .78) <= 1 ? Number(incident.confidence ?? .78) * 100 : Number(incident.confidence ?? .78)); const risk = /critical/i.test(incident.severity || '') ? 92 : /high/i.test(incident.severity || '') ? 76 : /medium/i.test(incident.severity || '') ? 54 : 28; const readings = telemetry?.readings || [];
  const events = [['Detection', incident.timestamp || incident.created_at, incident.incident_type || 'Anomaly detected', 'alert'], ['Sensor snapshot', null, incident.evidence || 'Condition deviation was correlated with the operating baseline.', 'signal'], ['Agent finding', null, incident.reasoning || 'Diagnostic agents are evaluating contributing process conditions.', 'agent'], ['Recommended action', null, incident.ai_recommendation || 'Keep the asset under focused monitoring until operator review.', 'action']];
  const pendingRec = Boolean(incident.ai_recommendation || incident.status !== 'closed');
  return <Box className="incident-os"><Box className="incident-os-head"><Box><Typography className="product-kicker">INCIDENT MANAGEMENT</Typography><Typography className="incident-os-title">Active investigation workspace</Typography></Box><Stack direction="row" spacing={1}><Button size="small" startIcon={<FilterListOutlined />}>Filters</Button><Button size="small" variant="contained" startIcon={<FactCheckOutlined />}>Decision log</Button></Stack></Box><Box className="incident-os-grid">
    <Paper className="incident-queue"><Box className="incident-queue-head"><Box><Typography className="product-kicker">INCIDENT QUEUE</Typography><Typography>{visible.length} active cases</Typography></Box><IconButton size="small"><MoreHorizOutlined /></IconButton></Box><TextField size="small" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search cases" slotProps={{ input: { startAdornment: <SearchOutlined fontSize="small" /> } }} /><TextField select size="small" value={severity} onChange={(e) => setSeverity(e.target.value)}><MenuItem value="all">All severities</MenuItem><MenuItem value="critical">Critical</MenuItem><MenuItem value="high">High</MenuItem><MenuItem value="medium">Medium</MenuItem></TextField><Box className="incident-queue-list" tabIndex={0} onKeyDown={(event) => { if (!visible.length) return; const ids = visible.map((item) => item.id); const idx = Math.max(0, ids.indexOf(selectedId)); if (event.key === 'ArrowDown') { event.preventDefault(); setSelectedId(ids[Math.min(ids.length - 1, idx + 1)]); } if (event.key === 'ArrowUp') { event.preventDefault(); setSelectedId(ids[Math.max(0, idx - 1)]); } if (event.key === 'Enter' && ids[idx]) setSelectedId(ids[idx]); }}>{visible.map((item, index) => <button type="button" onClick={() => setSelectedId(item.id)} key={item.id || index} className={`incident-queue-item ${incident.id === item.id ? 'selected' : ''}`}><Box><Status state={item.severity || item.status || 'open'} /><Typography>{formatTime(item.timestamp || item.created_at)}</Typography></Box><b>{label(item.incident_type || 'Operational event')}</b><Typography>{item.asset_name || item.asset_id || 'Asset identification pending'}</Typography><Box><span>Risk { /critical/i.test(item.severity || '') ? 92 : /high/i.test(item.severity || '') ? 76 : 54 }</span><span>{round(Number(item.confidence ?? .78) <= 1 ? Number(item.confidence ?? .78) * 100 : Number(item.confidence ?? .78))}% confidence</span></Box></button>)}</Box></Paper>
    <Paper className="investigation-timeline p8-inspector-swap" key={incident.id} ref={timelineRef}><Box className="investigation-head"><Box><Typography className="product-kicker">INCIDENT TIMELINE</Typography><Typography className="investigation-title">{label(incident.incident_type || 'Operational event')}</Typography><Typography variant="caption">Case {incident.id || 'under review'}  -  affected asset: <Button size="small" onClick={() => incident.asset_id && navigateTo(objectApi, navigate, 'assets', { assetId: incident.asset_id })}>{incident.asset_name || incident.asset_id || 'unresolved'}</Button></Typography><Stack direction="row" spacing={1} sx={{ mt: 1 }}><Button size="small" variant="contained" onClick={() => navigateTo(objectApi, navigate, 'investigation', { incidentId: incident.id, assetId: incident.asset_id || null, focusDecisionBar: true })}>View investigation</Button></Stack></Box><Status state={incident.status || incident.severity || 'open'} /></Box><Box className="incident-summary-strip"><Box><Typography>Severity</Typography><b>{label(incident.severity || 'Medium')}</b><ProvenanceBadge value={provenance} /></Box><Box><Typography>Risk</Typography><b className="risk-text">{risk}/100</b></Box><Box><Typography>Impact</Typography><b>{incident.impact || 'Production exposure'}</b></Box><Box><Typography>Confidence</Typography><b>{confidence}%</b></Box></Box><Box className="incident-timeline">{events.map(([title, time, detail, kind], index) => <Box className={`incident-event ${kind}`} key={title}><span>{index + 1}</span><Box><Typography>{title}<small>{time ? formatTime(time) : 'live evidence stream'}</small></Typography><Typography>{detail}</Typography>{title === 'Agent finding' && <Button size="small" onClick={() => setReasoning(!reasoning)} endIcon={<ExpandMoreOutlined />}>{reasoning ? 'Collapse reasoning' : 'Expand reasoning'}</Button>}{title === 'Agent finding' && reasoning && <motion.div className="incident-reasoning" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} transition={{ duration: 0.12 }}>{safeReasoning(incident.reasoning || 'The diagnostic workflow is correlating sensor deviation, asset condition, and maintenance history before proposing a root cause.')}</motion.div>}</Box></Box>)}</Box><Box className="dependency-graph"><Typography className="product-kicker">DEPENDENCY GRAPH</Typography><Box><span>Upstream feed</span><i /><strong>{incident.asset_name || 'Affected asset'}</strong><i /><span>Downstream unit</span></Box><Typography variant="caption">Process dependencies are highlighted to support containment decisions.</Typography></Box></Paper>
    <Paper className="incident-evidence"><Box className="incident-evidence-head"><Box><Typography className="product-kicker">EVIDENCE</Typography><Typography>Live case record</Typography></Box><Button size="small" startIcon={<PlayArrowOutlined />} onClick={() => setReplay(!replay)}>{replay ? 'Pause replay' : 'Replay telemetry'}</Button></Box><Box className="evidence-snapshot"><Box><Typography className="product-kicker">SENSOR SNAPSHOT</Typography><Typography>{replay ? 'Replaying incident window  -  2x' : 'Current historian window'}</Typography></Box><MiniGraph values={readings.map((reading) => reading.value)} area label={readings.length ? `${readings.length} captured samples` : 'No telemetry samples attached'} /></Box><Box className="evidence-list"><EvidenceItem icon={<DevicesOutlined />} label="Sensor snapshots" detail={incident.evidence ? 'Evidence packet attached' : 'Live baseline comparison'} /><EvidenceItem icon={<MemoryOutlined />} label="Agent findings" detail={`${confidence}% corroborated confidence`} /><EvidenceItem icon={<ArticleOutlined />} label="Photos & documents" detail={`${incident.documents_count || 2} related records`} /><EvidenceItem icon={<ShieldOutlined />} label="Audit trail" detail="Operator and agent actions recorded" /></Box><Box className="root-cause"><Typography className="product-kicker">ROOT CAUSE HYPOTHESIS</Typography><Typography>{incident.root_cause || incident.reasoning || 'Awaiting operator confirmation after diagnostic evidence is reviewed.'}</Typography></Box></Paper>
  </Box><Paper className="incident-bottom"><Box className="incident-bottom-tabs"><Button className="active" startIcon={<CommentOutlined />}>Comments</Button><Button startIcon={<FactCheckOutlined />}>Decisions</Button><Button>Logs</Button><Button>Approvals</Button><Button>Recommended actions</Button></Box><Box className="incident-bottom-body"><Box><Typography className="product-kicker">OPERATOR NOTES</Typography><Typography className="operator-note">No unresolved operator note is blocking this case. Add a decision or acknowledgement to continue the audit trail.</Typography><Button size="small" startIcon={<CommentOutlined />}>Add note</Button></Box><Box className="decision-track"><Typography className="product-kicker">DECISION TIMELINE</Typography><Typography><i />Detection logged <b>system</b></Typography><Typography><i />Evidence package assembled <b>diagnostic agent</b></Typography><Typography><i />Operator approval pending <b>control room</b></Typography></Box><DecisionHistory entries={objectApi.audit?.recentDecisions?.filter((entry) => !incident?.id || entry.incidentId === incident.id) || []} /></Box></Paper><EvidenceLineage facts={buildEvidenceFacts({ incident, stages: [] })} />{pendingRec ? <OperatorDecisionBar incident={incident} objectApi={objectApi} recommendation={incident.ai_recommendation} /> : null}</Box>;
}
